export const icons = {
    arrDown: require('./arr-down.png'),
    book: require('./book.png'),
    call: require('./call.png'),
    germanyFlag: require('./germany.png'),
    location: require('./location.png'),
    mail: require('./mail.png'),
    nigeriaFlag: require('./nigeria.png'),
    ukFlag: require('./uk.png'),
    ugandanFlag: require('./uganda.png'),
    tick: require('./tick.png'),
    quote: require('./quote.png'),
    phoneWhite: require('./phone.png'),
    mailWhite: require('./mail-white.png'),
    locationWhite: require('./location-white.png'),
    rightAngle: require('./right-angle.png'),
	calendar: require('./calendar.png'),
	profile: require('./profile.png'),
	star: require('./star.png'),
	money: require('./money.png'),
	enrollArr: require('./enroll-arr.png'),
	moneyWhite: require('./money-white.png'),
	arrowRight: require('./arrow-right.png'),
	duration: require('./duration.png'),
	lectures: require('./lectures.png'),
    stars: require('./stars.png'),
}
